config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :movies do
    resources :comments
    post 'add_to_watchlist'
    delete 'remove_from_watchlist'
  end

  resources :watchlist, only: %i[index destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :movie
  belongs_to :user
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  validates :title, :release_date, :poster_path, :overview, presence: true

  has_many :comments, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_and_belongs_to_many :watchlist, class_name: 'Movie', dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    movies_path
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: %i[create destroy]
  before_action :set_comment, only: [:destroy]

  def create
    @comment = @movie.comments.new(comment_params.merge(user: current_user))

    if @comment.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @movie }
      end
    else
      head :no_content
    end
  end

  def destroy
    if @comment.user == current_user
      @comment.destroy
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @movie }
      end
    else
      head :forbidden
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: %i[add_to_watchlist remove_from_watchlist]

  def index
    @response = MoviesService.new(params).index
  end

  def show
    @movie = MoviesService.new(params).show
  end

  def add_to_watchlist
    current_user.watchlist << @movie

    redirect_to movie_path(@movie)
  end

  def remove_from_watchlist
    current_user.watchlist.destroy(@movie)

    redirect_to movie_path(@movie)
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def movie_params
    params.permit(:query)
  end
end

app/controllers/watchlist_controller.rb
# frozen_string_literal: true

class WatchlistController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [:destroy]

  def index
    @movies_to_watch = current_user.watchlist
  end

  def destroy
    current_user.watchlist.destroy(@movie)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to watchlist_index_path }
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>" class="bg-white rounded-lg p-3 shadow mb-4 flex items-start">
  <div class="text-sm">
    <p class="font-bold mb-2"><%= comment.user.email %></p>
    <p class="text-gray-700"><%= comment.body %></p>
    <p class="text-gray-600 text-xs mt-2"><%= comment.created_at.strftime("%B %d, %Y %I:%M %p") %></p>
    <%= link_to 'Delete', movie_comment_path(movie, comment), class: 'text-white bg-red-500 p-1 rounded', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } if comment.user == current_user %>
  </div>
</div>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append('comments-list', partial: 'comment', locals: { comment: @comment, movie: @movie })%>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove(dom_id(@comment))%>

app/views/home/index.html.erb
<div class="mb-2"><%= link_to "Login", movies_path, class: 'text-xl underline' %> to continue to the application</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Header Section -->
    <header class="bg-blue-500 text-center py-4 text-white flex justify-between">
      <div class="space-x-3 ml-4">
        <%= link_to "My Watchlist", watchlist_index_path, class: 'text-xl underline hover:text-gray-200' %>
        <%= link_to "Movies", movies_path, class: 'text-xl underline hover:text-gray-200' %>
      </div>
      <div class=" space-x-5 mr-4">
        <% if user_signed_in? %>
          <%= "Logged in as : #{current_user&.email}" %>
          <%= link_to "Signout", destroy_user_session_path, data: { turbo_method: :delete } %>
        <% end %>
      </div>
    </header>

    <!-- Body Section -->
    <main class="container mx-auto py-10">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/movies/_movie_card.html.erb
<div class="flex flex-col bg-white rounded-lg shadow-md overflow-hidden">
  <div class="flex-shrink-0">
    <%= image_tag "https://image.tmdb.org/t/p/w300#{movie.poster_path}", class: "h-48 w-full object-cover", alt: "Movie poster" %>
  </div>
  <div class="p-6">
      <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold"><%= movie.title %></div>
      <p class="mt-1 text-gray-500">Release Date: <%= movie.release_date %></p>
      <p class="mt-1 text-gray-500">Rating: <%= movie.vote_average&.round(1)%></p>
      <div class="mt-4">
        <%= link_to "View Details", movie_path(movie.id), class: 'mt-4 w-full px-4 py-2 text-white bg-indigo-600 rounded hover:bg-indigo-500' %>
      </div>
  </div>
</div>

app/views/movies/index.html.erb
<%= form_with method: :get, class: 'w-full max-w-sm mx-auto' do |form| %>
  <div class="flex items-center border-b-2 border-blue-500 py-2">
    <%= form.text_field :query, placeholder: "Search movies", class: 'appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none' %>
    <%= form.submit "Search", class: 'flex-shrink-0 bg-blue-500 hover:bg-blue-700 border-blue-500 hover:border-blue-700 text-sm border-4 text-white py-1 px-2 rounded' %>
  </div>
<% end %>

<section id="movie-list" class="mt-10">
  <div class="grid grid-cols-3 gap-4 p-4">
    <%= render partial: 'movie_card', collection: @response.results, as: :movie %>
  </div>
</section>

app/views/movies/show.html.erb
<div class="md:flex bg-white rounded-lg p-6">
    <%= image_tag "https://image.tmdb.org/t/p/w500#{@movie.poster_path}", class: "h-48 w-full md:w-48 object-cover md:mr-6", alt: "Movie poster" %>
    <div class="w-full">
        <h2 class="text-xl font-semibold text-gray-900"><%= @movie.title%></h2>
        <p class="text-gray-700 mt-2">Release date: <%= @movie.release_date%></p>
        <p class="text-gray-700 mt-2">Overview: <%= @movie.overview%></p>
        <div class="mt-2">
          <% if current_user.watchlist.exists?(@movie.id) %>
            <%= link_to 'Remove from watchlist', movie_remove_from_watchlist_path(@movie), data: { turbo_method: :delete }, class: "text-white bg-red-700 rounded px-2 py-2" %>  
          <% else %>
            <%= link_to 'Add to watchlist', movie_add_to_watchlist_path(@movie), data: { turbo_method: :post }, class: "text-white bg-green-700 rounded px-2 py-2" %>
          <% end %>
        </div>
    </div>
</div>

<div class="mt-10">
    <h2 class="text-xl font-semibold text-gray-900 mb-4">Comments</h2>

    <turbo-frame id="new_comment">
      <%= form_with model: [@movie, Comment.new], data: { turbo_frame: "new_comment" } do |form| %>
        <div class="mb-5">
          <%= form.text_area :body, class: "w-full border rounded focus:outline-none focus:ring-2 p-3", rows: "3" , placeholder: "Add a comment" %>
          <%= form.submit "Submit", class: "mt-2 w-auto px-4 py-2 text-white bg-indigo-600 rounded hover:bg-indigo-500" %>
        </div>
      <% end %>
    </turbo-frame>
    
    <div id="comments-list">
      <%= render partial: 'comments/comment', collection: @movie.comments, as: :comment, locals: { movie: @movie } %>
    </div>
</div>

app/views/watchlist/_movie_card.html.erb
<div id="<%= dom_id(movie) %>" class="bg-white rounded-lg p-6 shadow mb-4 flex justify-between items-center">
  <div class="w-48">
      <%= image_tag "https://image.tmdb.org/t/p/w300#{movie.poster_path}", class: "h-24 w-full object-cover", alt: "Movie poster" %>
  </div>
  <div class="w-1/2">
      <h2 class="text-xl font-semibold text-gray-900"><%= movie.title %></h2>
      <p class="text-gray-700 mt-2">Overview <%= movie.overview %></p>
  </div>
  <%= link_to 'Remove', watchlist_path(movie), class: 'text-white bg-red-700 rounded p-2', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }  %>
</div>

app/views/watchlist/destroy.turbo_stream.erb
<%= turbo_stream.remove(dom_id(@movie))%>

app/views/watchlist/index.html.erb
<div >
    <% if @movies_to_watch.present? %>
        <h1>Here's your watchlist</h1>
        <%= render partial: 'movie_card', collection: @movies_to_watch, as: :movie %>
    <% else %>
        <h1>Your watchlist is empty.</h2>
    <% end %>
</div>